### PR TITLE
Port subscribe widget

### PR DESCRIPTION
**Pull request by josiahsprague**
~~Based on `dr3JdTPS-migration-template` which should be merged into master first~~

Rebased on #3

### CODE REVIEW

**Comment by josiahsprague** [comment]
See https://github.com/SparkartGroupInc/jungle-solidus/pull/16

**Comment by pushred** [comment]
Ready for review!

Picking up where Josiah left off, I adapted this to leverage the new widget helpers for handling the placeholders. The advantage of this is consistency in the developer UX with all the other widgets. The stubbed JS files are a bit silly, but there isn't a way around that really and maybe they'll serve more of a purpose later.

Alerts have also been updated to follow the Clique Tools markup and general implementation:

 - The "widgets" mark the desired position(s) of the alert on the page. In some cases an alert can be intentionally repeated on a header and footer.

 - Only 1 alert message may be shown at a time — just like Rails flash messaging.

 - Support for multiple kinds of alerts, requires https://github.com/blocks/alerter/pull/6

I also added support for input images. Originally I was like "we'll just do it in CSS", but it turned out to be easier to support as another helper param. Part of the solution requires switching `<input>` to `<button>~ which allows text or images. Minor CSS changes to update selectors will be needed. I added a new common stylesheet to reset browser styling on that element and hide empty placeholders. This'll be used for any similar global CSS.

The order of the compiled JS has also been reversed, as in the case of the Big Talk site (and likely others) there was some JS faking a placeholder on the subscribe input. This won't be an issue so long as we never use jQuery in the Browserify bundle. It's possible!

This can be seen in action in the bigtalkmusic.com [subscribe-widget branch](https://github.com/sparkartgroupinc/bigtalkmusic.com/tree/subscribe-widget).

**Comment by josiahsprague** [comment]
Seeing the following error on bigtalk;
`http://bigtalkmusic.dev/images/widgets/bg-optin.png 404 (Not Found)`

**Comment by josiahsprague** [comment]
Left a few comments, but looks good! 👍

**Pull request merged**
