### PR TITLE
fix asset helper

### PR DESCRIPTION
**Pull request by josiahsprague**
This fixes the issue that @pushred and others were having that was preventing sites from starting up. (https://github.com/SparkartGroupInc/bigtalkmusic.com/pull/2)

check if pageAssets exists before trying to access it's properties

### CODE REVIEW

**Comment by pushred** [comment]
:+1: works on Big Talk. Though how did it ever work for you if you had the same config as well?

**Comment by josiahsprague** [comment]
Before we merge, I'd like to use this PR to make the changes that are a part of;

- [ ] simplify structure of site.yml

**Comment by josiahsprague** [comment]
Rebased on #7

**Comment by pushred** [comment]
Can you add some handling around sections? I didn't have any defined in my config and ran into this:

```
TypeError: Cannot read property 'undefined' of undefined
    at Object.module.exports (/Users/eric/dev/sites/janetjackson.com/node_modules/jungle-solidus/helpers/assets.js:11:36)
    at Object.eval (eval at <anonymous> (/Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/handlebars/lib/handlebars/compiler/compiler.js:579:23), <anonymous>:63:72)
    at /Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/handlebars/lib/handlebars/runtime.js:38:33
    at /Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1294:21
    at ExpressHandlebars._renderTemplate (/Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/express-handlebars/lib/express-handlebars.js:310:12)
    at ExpressHandlebars.<anonymous> (/Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/express-handlebars/lib/express-handlebars.js:184:21)
    at /Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/express-handlebars/node_modules/promise/lib/core.js:33:15
    at flush (/Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/express-handlebars/node_modules/promise/node_modules/asap/asap.js:27:13)
    at /Users/eric/dev/sites/janetjackson.com/node_modules/solidus/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (node.js:442:13)
```

Some sites may not define any sections and we shouldn't require full config before a server can be started. You can stub it out of course, but the error handling is pretty bad. It'd be easier to just make it optional.

**Comment by pushred** [comment]
Every time I refresh a page with a page asset, this happens:

```html
<link rel="stylesheet" href="./assets/styles/./assets/styles/./assets/styles/./assets/styles/./assets/styles/skin-numberones.css" />```

**Comment by josiahsprague** [comment]
I added some checks around sections to see if they keys exist in site.yml before using them. And I moved `site = yaml.safeLoad(fs.readFileSync('site.yml'));` inside the asset helper so we don't run into the `./assets/styles/./assets/styles/./assets/styles/` problem. I'm running into some problems with the editorial widget now and I haven't been able to determine the cause.

```
TypeError: Cannot read property 'pages' of undefined
    at Object.module.exports (/vagrant/bigtalkmusic/node_modules/jungle-solidus/widgets/editorial/default_options.js:2:68)
```

I don't think they're related to these changes, but I'm still working on isolating the error.

**Comment by pushred** [comment]
You moved that from the preprocessor? The widgets depend on `site` being in the global context.

**Comment by josiahsprague** [comment]
No, I didn't move it. I wrote the first version of this helper before `site` was in the global context. But if that's supposed to be in the global context now, I can use that here.

**Comment by pushred** [comment]
Ah, yeah it will reliably be there because all the widgets break without it.

**Comment by pushred** [comment]
Using https://github.com/SparkartGroupInc/jungle-solidus/commit/cd4f62f090e3d7f653d8038a859c53fd38467ac3 I can override styles per page and section. After the latest commit I can't.

In either revision I can't override scripts per page or assign pages to sections.

**Comment by pushred** [comment]
Page overrides are fine now, wasn't working with a leading `/` I had been using.

**Comment by josiahsprague** [comment]
Updated the helper to pull asset paths from global context rather than directly from site.yml

**Comment by josiahsprague** [comment]
Pushed a proper fix for the `./assets/styles/./assets/styles/./assets/styles/` problem by cloning the `site` object before modifying it, since it's kept in memory until the server is restarted.

**Comment by pushred** [comment]
:+1:

**Pull request merged**
